mod 'puppetlabs-stdlib',
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
    :tag => "4.16.0"
mod 'puppetlabs-apt',
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
{{~#puppetCollection}}
    :tag => "3.0.0"
{{~/puppetCollection}}
{{~^puppetCollection}}
    :tag => "2.4.0"
{{~/puppetCollection}}
