# -*- mode: ruby -*-
# vi: set ft=ruby :

# from https://github.com/blinkreaction/boot2docker-vagrant/blob/master/Vagrantfile
plugins = %w{vagrant-r10k}
need_restart = false
plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system "#{$0} plugin install #{plugin}"
    need_restart = true
  end
end
exec($0, *ARGV) if need_restart

Vagrant.configure(2) do |config|
  config.vm.box = "{{ configVmBox }}"

  config.r10k.puppet_dir = "puppet/environments/default"
  config.r10k.puppetfile_path = "puppet/environments/default/Puppetfile"
  config.r10k.module_path = "puppet/environments/default/modules"

  # http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
  config.vm.provision "fix-no-tty", type: "shell", privileged: false,
                      path: "vagrant/fix-no-tty.sh"

  # from https://github.com/hashicorp/puppet-bootstrap
  config.vm.provision "install-puppet", type: "shell",
                      env: {:PUPPET_COLLECTION => '{{ puppetCollection }}',
                            :DEBIAN_FRONTEND => 'noninteractive'},
                      path: "vagrant/ubuntu.sh"

{{~^puppetCollection}}

  # https://tickets.puppetlabs.com/browse/PUP-2566
  config.vm.provision "fix-templatedir",
                      type: "shell",
                      inline: "sed -i -e '/templatedir/d' /etc/puppet/puppet.conf"
{{~/puppetCollection}}

  # finally run puppet
  config.vm.provision "puppet" do |puppet|
{{~^puppetCollection}}
    puppet.hiera_config_path = "puppet/environments/default/hiera.yaml"
    puppet.manifest_file = 'site.pp'
    puppet.manifests_path = 'puppet/environments/default/manifests'
    puppet.options = '--parser future'
    puppet.module_path = ['puppet/environments/default/site',
                          'puppet/environments/default/modules']
{{~/puppetCollection}}
    puppet.environment = "default"
    puppet.environment_path = "puppet/environments"
  end
end
